//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HS_THPT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_GV_HS_THPTEntities : DbContext
    {
        public QL_GV_HS_THPTEntities()
            : base("name=QL_GV_HS_THPTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblGiangday> tblGiangday { get; set; }
        public virtual DbSet<tblGiaovien> tblGiaovien { get; set; }
        public virtual DbSet<tblHocSinh> tblHocSinh { get; set; }
        public virtual DbSet<tblLop> tblLop { get; set; }
        public virtual DbSet<tblMonhoc> tblMonhoc { get; set; }
        public virtual DbSet<tblPhanquyen> tblPhanquyen { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
    
        public virtual ObjectResult<GetAllHS_Result> GetAllHS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllHS_Result>("GetAllHS");
        }
    
        public virtual ObjectResult<GetAllUser_Result> GetAllUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllUser_Result>("GetAllUser");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int SP_ThayDoi(string ma, string ten, Nullable<bool> gT, Nullable<System.DateTime> ngaysinh, string malop, string dantoc, string tongiao, string diachi)
        {
            var maParameter = ma != null ?
                new ObjectParameter("Ma", ma) :
                new ObjectParameter("Ma", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var gTParameter = gT.HasValue ?
                new ObjectParameter("GT", gT) :
                new ObjectParameter("GT", typeof(bool));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("Ngaysinh", ngaysinh) :
                new ObjectParameter("Ngaysinh", typeof(System.DateTime));
    
            var malopParameter = malop != null ?
                new ObjectParameter("Malop", malop) :
                new ObjectParameter("Malop", typeof(string));
    
            var dantocParameter = dantoc != null ?
                new ObjectParameter("Dantoc", dantoc) :
                new ObjectParameter("Dantoc", typeof(string));
    
            var tongiaoParameter = tongiao != null ?
                new ObjectParameter("Tongiao", tongiao) :
                new ObjectParameter("Tongiao", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("Diachi", diachi) :
                new ObjectParameter("Diachi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThayDoi", maParameter, tenParameter, gTParameter, ngaysinhParameter, malopParameter, dantocParameter, tongiaoParameter, diachiParameter);
        }
    
        public virtual int SP_ThemHS1(string ma, string ten, string gT, Nullable<System.DateTime> ngaysinh, string malop, string dantoc, string tongiao, string diachi)
        {
            var maParameter = ma != null ?
                new ObjectParameter("Ma", ma) :
                new ObjectParameter("Ma", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var gTParameter = gT != null ?
                new ObjectParameter("GT", gT) :
                new ObjectParameter("GT", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("Ngaysinh", ngaysinh) :
                new ObjectParameter("Ngaysinh", typeof(System.DateTime));
    
            var malopParameter = malop != null ?
                new ObjectParameter("Malop", malop) :
                new ObjectParameter("Malop", typeof(string));
    
            var dantocParameter = dantoc != null ?
                new ObjectParameter("Dantoc", dantoc) :
                new ObjectParameter("Dantoc", typeof(string));
    
            var tongiaoParameter = tongiao != null ?
                new ObjectParameter("Tongiao", tongiao) :
                new ObjectParameter("Tongiao", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("Diachi", diachi) :
                new ObjectParameter("Diachi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemHS1", maParameter, tenParameter, gTParameter, ngaysinhParameter, malopParameter, dantocParameter, tongiaoParameter, diachiParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SP_XoaHS(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("Ma", ma) :
                new ObjectParameter("Ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XoaHS", maParameter);
        }
    
        public virtual int SuaChiTietDiem(string mahs, string mamh, Nullable<int> hocky, Nullable<double> diemhs1, Nullable<double> diemhs2, Nullable<double> diemhs3, Nullable<double> diemtb)
        {
            var mahsParameter = mahs != null ?
                new ObjectParameter("mahs", mahs) :
                new ObjectParameter("mahs", typeof(string));
    
            var mamhParameter = mamh != null ?
                new ObjectParameter("mamh", mamh) :
                new ObjectParameter("mamh", typeof(string));
    
            var hockyParameter = hocky.HasValue ?
                new ObjectParameter("hocky", hocky) :
                new ObjectParameter("hocky", typeof(int));
    
            var diemhs1Parameter = diemhs1.HasValue ?
                new ObjectParameter("diemhs1", diemhs1) :
                new ObjectParameter("diemhs1", typeof(double));
    
            var diemhs2Parameter = diemhs2.HasValue ?
                new ObjectParameter("diemhs2", diemhs2) :
                new ObjectParameter("diemhs2", typeof(double));
    
            var diemhs3Parameter = diemhs3.HasValue ?
                new ObjectParameter("diemhs3", diemhs3) :
                new ObjectParameter("diemhs3", typeof(double));
    
            var diemtbParameter = diemtb.HasValue ?
                new ObjectParameter("diemtb", diemtb) :
                new ObjectParameter("diemtb", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaChiTietDiem", mahsParameter, mamhParameter, hockyParameter, diemhs1Parameter, diemhs2Parameter, diemhs3Parameter, diemtbParameter);
        }
    
        public virtual int ThemChiTietDiem(string mahs, string mamh, Nullable<int> hocky, Nullable<double> diemhs1, Nullable<double> diemhs2, Nullable<double> diemhs3, Nullable<double> diemtb)
        {
            var mahsParameter = mahs != null ?
                new ObjectParameter("mahs", mahs) :
                new ObjectParameter("mahs", typeof(string));
    
            var mamhParameter = mamh != null ?
                new ObjectParameter("mamh", mamh) :
                new ObjectParameter("mamh", typeof(string));
    
            var hockyParameter = hocky.HasValue ?
                new ObjectParameter("hocky", hocky) :
                new ObjectParameter("hocky", typeof(int));
    
            var diemhs1Parameter = diemhs1.HasValue ?
                new ObjectParameter("diemhs1", diemhs1) :
                new ObjectParameter("diemhs1", typeof(double));
    
            var diemhs2Parameter = diemhs2.HasValue ?
                new ObjectParameter("diemhs2", diemhs2) :
                new ObjectParameter("diemhs2", typeof(double));
    
            var diemhs3Parameter = diemhs3.HasValue ?
                new ObjectParameter("diemhs3", diemhs3) :
                new ObjectParameter("diemhs3", typeof(double));
    
            var diemtbParameter = diemtb.HasValue ?
                new ObjectParameter("diemtb", diemtb) :
                new ObjectParameter("diemtb", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemChiTietDiem", mahsParameter, mamhParameter, hockyParameter, diemhs1Parameter, diemhs2Parameter, diemhs3Parameter, diemtbParameter);
        }
    
        public virtual int XoaChiTietDiem(string mahs, string mamh, Nullable<int> hocky)
        {
            var mahsParameter = mahs != null ?
                new ObjectParameter("mahs", mahs) :
                new ObjectParameter("mahs", typeof(string));
    
            var mamhParameter = mamh != null ?
                new ObjectParameter("mamh", mamh) :
                new ObjectParameter("mamh", typeof(string));
    
            var hockyParameter = hocky.HasValue ?
                new ObjectParameter("hocky", hocky) :
                new ObjectParameter("hocky", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaChiTietDiem", mahsParameter, mamhParameter, hockyParameter);
        }
    
        public virtual int XOAGIAOVIEN(string maGV)
        {
            var maGVParameter = maGV != null ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOAGIAOVIEN", maGVParameter);
        }
    
        public virtual int ThemHS(string maHS, string tenHS, string gT, Nullable<System.DateTime> ngaySinh, string diaChi, string danToc, string tonGiao, string maLop)
        {
            var maHSParameter = maHS != null ?
                new ObjectParameter("MaHS", maHS) :
                new ObjectParameter("MaHS", typeof(string));
    
            var tenHSParameter = tenHS != null ?
                new ObjectParameter("TenHS", tenHS) :
                new ObjectParameter("TenHS", typeof(string));
    
            var gTParameter = gT != null ?
                new ObjectParameter("GT", gT) :
                new ObjectParameter("GT", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var danTocParameter = danToc != null ?
                new ObjectParameter("DanToc", danToc) :
                new ObjectParameter("DanToc", typeof(string));
    
            var tonGiaoParameter = tonGiao != null ?
                new ObjectParameter("TonGiao", tonGiao) :
                new ObjectParameter("TonGiao", typeof(string));
    
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemHS", maHSParameter, tenHSParameter, gTParameter, ngaySinhParameter, diaChiParameter, danTocParameter, tonGiaoParameter, maLopParameter);
        }
    
        public virtual int Them_HS(string maHS, string tenHS, string gT, Nullable<System.DateTime> ngaySinh, string diaChi, string danToc, string tonGiao, string maLop)
        {
            var maHSParameter = maHS != null ?
                new ObjectParameter("MaHS", maHS) :
                new ObjectParameter("MaHS", typeof(string));
    
            var tenHSParameter = tenHS != null ?
                new ObjectParameter("TenHS", tenHS) :
                new ObjectParameter("TenHS", typeof(string));
    
            var gTParameter = gT != null ?
                new ObjectParameter("GT", gT) :
                new ObjectParameter("GT", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var danTocParameter = danToc != null ?
                new ObjectParameter("DanToc", danToc) :
                new ObjectParameter("DanToc", typeof(string));
    
            var tonGiaoParameter = tonGiao != null ?
                new ObjectParameter("TonGiao", tonGiao) :
                new ObjectParameter("TonGiao", typeof(string));
    
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Them_HS", maHSParameter, tenHSParameter, gTParameter, ngaySinhParameter, diaChiParameter, danTocParameter, tonGiaoParameter, maLopParameter);
        }
    
        public virtual int SuaHS(string maHS, string tenHS, string gT, Nullable<System.DateTime> ngaySinh, string diaChi, string danToc, string tonGiao, string maLop)
        {
            var maHSParameter = maHS != null ?
                new ObjectParameter("MaHS", maHS) :
                new ObjectParameter("MaHS", typeof(string));
    
            var tenHSParameter = tenHS != null ?
                new ObjectParameter("TenHS", tenHS) :
                new ObjectParameter("TenHS", typeof(string));
    
            var gTParameter = gT != null ?
                new ObjectParameter("GT", gT) :
                new ObjectParameter("GT", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var danTocParameter = danToc != null ?
                new ObjectParameter("DanToc", danToc) :
                new ObjectParameter("DanToc", typeof(string));
    
            var tonGiaoParameter = tonGiao != null ?
                new ObjectParameter("TonGiao", tonGiao) :
                new ObjectParameter("TonGiao", typeof(string));
    
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaHS", maHSParameter, tenHSParameter, gTParameter, ngaySinhParameter, diaChiParameter, danTocParameter, tonGiaoParameter, maLopParameter);
        }
    
        public virtual int Xoa(string maHS)
        {
            var maHSParameter = maHS != null ?
                new ObjectParameter("MaHS", maHS) :
                new ObjectParameter("MaHS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Xoa", maHSParameter);
        }
    
        public virtual int Sua_HS(string maHS, string tenHS, string gT, Nullable<System.DateTime> ngaySinh, string diaChi, string danToc, string tonGiao, string maLop)
        {
            var maHSParameter = maHS != null ?
                new ObjectParameter("MaHS", maHS) :
                new ObjectParameter("MaHS", typeof(string));
    
            var tenHSParameter = tenHS != null ?
                new ObjectParameter("TenHS", tenHS) :
                new ObjectParameter("TenHS", typeof(string));
    
            var gTParameter = gT != null ?
                new ObjectParameter("GT", gT) :
                new ObjectParameter("GT", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var danTocParameter = danToc != null ?
                new ObjectParameter("DanToc", danToc) :
                new ObjectParameter("DanToc", typeof(string));
    
            var tonGiaoParameter = tonGiao != null ?
                new ObjectParameter("TonGiao", tonGiao) :
                new ObjectParameter("TonGiao", typeof(string));
    
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sua_HS", maHSParameter, tenHSParameter, gTParameter, ngaySinhParameter, diaChiParameter, danTocParameter, tonGiaoParameter, maLopParameter);
        }
    
        public virtual ObjectResult<GetAllGV_Result> GetAllGV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllGV_Result>("GetAllGV");
        }
    
        public virtual ObjectResult<GetHSBySearch_Result> GetHSBySearch(string maHS, string ten, string maLop)
        {
            var maHSParameter = maHS != null ?
                new ObjectParameter("MaHS", maHS) :
                new ObjectParameter("MaHS", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHSBySearch_Result>("GetHSBySearch", maHSParameter, tenParameter, maLopParameter);
        }
    
        public virtual int SuaGV(string maGV, string tenGV, string gT, Nullable<System.DateTime> ngaySinh, string sDT, string diaChi, Nullable<int> luong, string maMon)
        {
            var maGVParameter = maGV != null ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(string));
    
            var tenGVParameter = tenGV != null ?
                new ObjectParameter("TenGV", tenGV) :
                new ObjectParameter("TenGV", typeof(string));
    
            var gTParameter = gT != null ?
                new ObjectParameter("GT", gT) :
                new ObjectParameter("GT", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(int));
    
            var maMonParameter = maMon != null ?
                new ObjectParameter("MaMon", maMon) :
                new ObjectParameter("MaMon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaGV", maGVParameter, tenGVParameter, gTParameter, ngaySinhParameter, sDTParameter, diaChiParameter, luongParameter, maMonParameter);
        }
    
        public virtual int ThemGV(string maGV, string tenGV, string gT, Nullable<System.DateTime> ngaySinh, string sDT, string diaChi, Nullable<int> luong, string maMon)
        {
            var maGVParameter = maGV != null ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(string));
    
            var tenGVParameter = tenGV != null ?
                new ObjectParameter("TenGV", tenGV) :
                new ObjectParameter("TenGV", typeof(string));
    
            var gTParameter = gT != null ?
                new ObjectParameter("GT", gT) :
                new ObjectParameter("GT", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(int));
    
            var maMonParameter = maMon != null ?
                new ObjectParameter("MaMon", maMon) :
                new ObjectParameter("MaMon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemGV", maGVParameter, tenGVParameter, gTParameter, ngaySinhParameter, sDTParameter, diaChiParameter, luongParameter, maMonParameter);
        }
    
        public virtual int XoaGV(string maGV)
        {
            var maGVParameter = maGV != null ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaGV", maGVParameter);
        }
    }
}
