//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HS_THPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGiangday
    {
        public string MaGV { get; set; }
        public string MaLop { get; set; }
        public int Thu { get; set; }
        public int Tietday { get; set; }
    
        public virtual tblGiaovien tblGiaovien { get; set; }
        public virtual tblLop tblLop { get; set; }
    }
}
