//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HS_THPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGiaovien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGiaovien()
        {
            this.tblGiangday = new HashSet<tblGiangday>();
            this.tblLop = new HashSet<tblLop>();
        }
    
        public string MaGV { get; set; }
        public string TenGV { get; set; }
        public string GT { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> Luong { get; set; }
        public string MaMon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGiangday> tblGiangday { get; set; }
        public virtual tblMonhoc tblMonhoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLop> tblLop { get; set; }
    }
}
