//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HS_THPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHocSinh
    {
        public string MaHS { get; set; }
        public string TenHS { get; set; }
        public string GT { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public string MaLop { get; set; }
    
        public virtual tblLop tblLop { get; set; }
    }
}
