//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HS_THPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLop()
        {
            this.tblGiangday = new HashSet<tblGiangday>();
            this.tblHocSinh = new HashSet<tblHocSinh>();
        }
    
        public string MaLop { get; set; }
        public string TenLop { get; set; }
        public string GVCN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGiangday> tblGiangday { get; set; }
        public virtual tblGiaovien tblGiaovien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHocSinh> tblHocSinh { get; set; }
    }
}
