//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HS_THPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string MaGV { get; set; }
        public int Quyen { get; set; }
    
        public virtual tblPhanquyen tblPhanquyen { get; set; }
    }
}
